# Generated by Django 3.2 on 2023-05-02 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_on', models.TimeField()),
                ('end_on', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PomodoroTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('is_pending', models.BooleanField(default=True)),
                ('pomodoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomodoro_app.pomodoro')),
            ],
        ),
    ]
