# Generated by Django 3.2 on 2023-05-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro_app', '0007_alter_pomodorotask_pomodoro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodoro',
            name='end_on',
        ),
        migrations.RemoveField(
            model_name='pomodoro',
            name='start_on',
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='pomodoro_duration',
            field=models.IntegerField(default=25),
        ),
    ]
