# Generated by Django 3.2 on 2023-05-03 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro_app', '0009_auto_20230503_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorotask',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='pomodorotask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='end_on',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 5, 3, 22, 28, 42, 880991)),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='start_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 3, 22, 28, 42, 880991)),
        ),
    ]
