# Generated by Django 3.2 on 2023-05-04 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro_app', '0011_auto_20230504_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='end_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 4, 23, 26, 43, 306071), null=True),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='start_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 4, 23, 26, 43, 306071)),
        ),
    ]
