# Generated by Django 3.2 on 2023-05-04 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro_app', '0014_auto_20230504_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='end_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='start_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 4, 23, 30, 39, 726469)),
        ),
    ]
